version: "3.8"

services:
  monitor:
    image: itzg/mc-monitor
    restart: unless-stopped
    command: export-for-prometheus
    environment:
      EXPORT_SERVERS: heresy-contraptions
      DEBUG: "true"
    depends_on:
      - heresy-contraptions
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.1
    restart: unless-stopped
    ports:
      - "8180:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-tsdb:/prometheus
    depends_on:
      - monitor
  grafana:
    image: grafana/grafana-oss:${GRAFANA_VERSION:-8.3.3}
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-lib:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./dashboards:/etc/grafana/dashboards
    depends_on:
      - prometheus
  heresy-contraptions:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      # Default minecraft server port
      - "25565:25565"
      # Voice chat port
      - "24454:24454/udp"
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      FORGE_VERSION: "47.2.0"
      VERSION: "1.20.1"
      MEMORY: 10G
      MAX_MEMORY: 12G
      SERVER_NAME: "ShitFuck 2 Electric Bungaloo"
      MOTD: "Sounds gay, I'm in"
      ICON: "https://cdn.discordapp.com/emojis/959558350532657212.gif"

      TZ: "Europe/Paris"
      
      #Delete old logs
      ENABLE_ROLLING_LOGS: "true"

      #World name
      LEVEL: "Ohio"

      #View distance in chunks
      VIEW_DISTANCE: 20
      
      #Disable spawn protection
      SPAWN_PROTECTION: 0
      #Set default gamemode to creative
      MODE: survival

      #Get the mods from the txt file
      MODS_FILE: /extras/mods.txt
      #Clear old mods
      REMOVE_OLD_MODS: "TRUE"
      REMOVE_OLD_MODS_EXCLUDE: ""

      OVERRIDE_WHITELIST: "true"
      ENABLE_WHITELIST: "true"
      EXISTING_WHITELIST_FILE: MERGE
      WHITELIST: |
        CheeseMcBaguette
        XeonMations
        Willoguns
        LukaszL
        captainatom931
        Apothikarios
        Josinosle
        BogdanBlazkowiz
        vega_D
        Drdielan

      EXISTING_OPS_FILE: MERGE
      OPS: |
        CheeseMcBaguette
        XeonMations
  
    volumes:
    # use a named, managed volume for data volume
    - ./data:/data

    # attach local host directory "mods" in same directory as this compose file
    # all mods in this directory get copied into /data/mods at startup
    # - ./mods:/mods:ro

    # attach local host directory "config" in same directory as this compose file
    # all config files in this directory get copied into /data/config at startup
    - ./config:/config:ro

    # attach the mods.txt file to the /extras/mods.txt path inside /data
    # mods.txt file get copied into /data/extras/mods.txt at startup
    - ./mods.txt:/extras/mods.txt:ro
volumes:
  data: {}
  prometheus-tsdb: {}
  grafana-lib: {}
networks:
  localprom:
    driver: bridge